version: "3.7"
services:
  central-ledger:
    build:
      dockerfile: test-integration.Dockerfile
      context: .
      cache_from:
        - mojaloop/central-ledger
        - central-ledger
        - central-ledger:test
    container_name: cl_central-ledger
    links:
      - mysql
      - kafka
    ports:
      - "3001:3001"
    volumes:
      - ./docker/central-ledger/default.json:/opt/central-ledger/config/default.json
      - ./test:/opt/central-ledger/test
      - ./src:/opt/central-ledger/src
      # - ./node_modules:/opt/central-ledger/node_modules
    environment:
      - CLEDG_MONGODB__DISABLED=true
      # Disable audit logs - makes it too verbose
      - EVENT_SDK_LOG_FILTER="log:info, log:warning, log:error"
    command:
      - tail
      - -f
      - /dev/null
